version: '3'
services:
    nginx:
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        depends_on:
            - backend
        ports:
            - 80:80
        volumes:
            - ./server/media:/nginx/media
    server:
        build:
            context: ./
            dockerfile: ./server/Dockerfile
        command: gunicorn config.wsgi -c ./config/gunicorn.py
        volumes:
            - ./server/media:/server/media
        depends_on:
            - db
            - frontend
        environment:
            DEBUG: 'False'
            DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
            BROKER_URL: 'amqp://user:password@rabbitmq:5672/my_vhost'
        env_file:
            - ./.env

    db:
        image: postgres:11.2
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres

    client:
        build:
            context: ./
            dockerfile: ./client/Dockerfile
        volumes:
            - ./client:/client
        ports:
            - 8080:8080
        command: yarn serve
