# Generated by Django 3.0.8 on 2020-08-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='promo/')),
            ],
            options={
                'verbose_name': 'Изображение на слайдер',
                'verbose_name_plural': 'Изображения на слайдер',
            },
        ),
    ]
