# Generated by Django 3.0.8 on 2020-09-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', 'data_migrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promo',
            options={'ordering': ('id',), 'verbose_name': 'Изображение на слайдер', 'verbose_name_plural': 'Изображения на слайдер'},
        ),
    ]
