# Generated by Django 3.0.8 on 2020-08-31 14:15
import csv
import os

import requests
from django.core.files.base import ContentFile
from django.db import migrations

from apps.dishes import parser
from apps.promo.models import Promo


def add_promo(apps, schema_editor):
    queryset = Promo.objects.all()
    if not queryset.count():
        if not os.path.isfile('./csv/promo.csv'):
            parser.main()
    with open('./csv/promo.csv', 'r') as file:
        reader = csv.reader(file)
        lst = list(reader)
        for row in lst:
            Promo.objects.get_or_create(name=row[0])
            # загружаем в модель изображения по ссылкам
            response = requests.get(row[1])
            promo = Promo.objects.get(name=row[0])
            promo.image.save(row[0], ContentFile(response.content), save=True)


class Migration(migrations.Migration):
    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_promo),
    ]
